FROM bde2020/spark-worker:3.0.0-hadoop3.2

RUN mkdir /tmp/python/ && cd /tmp/python \
&& wget https://www.python.org/ftp/python/3.8.5/Python-3.8.5.tgz \
&& tar zxvf Python-3.8.5.tgz && cd Python-3.8.5 \
&& apk del python3 \
&& apk add --no-cache gcc g++ make libffi-dev openssl-dev zlib-dev \
&& ./configure --prefix=/usr --enable-optimizations \
&& make && make install \
&& apk del gcc g++ make libffi-dev openssl-dev zlib-dev \ 
&& cd /tmp && rm -rf python
